import Modal from 'bootstrap/js/dist/modal.js';
import '../../blocks/modules/header/header.js';
import "../../blocks/modules/footer/footer.js";
import "../../blocks/modules/input/input.js";
import "../../blocks/modules/tabs/tabs.js";
import "../../blocks/modules/slider/slider.js";
import "../../blocks/modules/compilation/compilation.js";
import "../../blocks/modules/search-block/search-block.js";
import "../../blocks/modules/catalog/catalog.js";
import "../../blocks/modules/modal/modal.js";
import "../../blocks/modules/form/form.js";
import "../../blocks/modules/get-up/get-up.js";
import "../../blocks/modules/catalog-filter/catalog-filter.js";
import "../../blocks/modules/catalog-page/catalog-page.js";
import "../../blocks/modules/catalog-tags/catalog-tags.js";
import "../../blocks/modules/catalog-description/catalog-description.js";
import "../../blocks/modules/catalog-item/catalog-item.js";
import "../../blocks/modules/product-control/product-control.js";
import "../../blocks/modules/color-choose/color-choose.js";
import "../../blocks/modules/product-page/increase-img-product.js";
import "../../blocks/modules/cart/cart.js";
import "../../blocks/modules/partners/partners.js";
import "../../blocks/modules/contacts-page/contacts-page.js";
import "../../blocks/modules/favorite/favorite-page.js";
import "../../blocks/modules/favorite-item/favorite-item.js";
import "../../blocks/modules/favorite-filter/favorite-filter.js";

import "../../blocks/modules/thread/thread.js";
