import '../../blocks/modules/header/header.js'
import "../../blocks/modules/footer/footer.js";
import "../../blocks/modules/input/input.js";
import "../../blocks/modules/tabs/tabs.js";
import "../../blocks/modules/slider/slider.js";
import "../../blocks/modules/compilation/compilation.js";
import "../../blocks/modules/search-block/search-block.js";
import "../../blocks/modules/catalog/catalog.js";
import "../../blocks/modules/modal/modal.js";
import "../../blocks/modules/form/form.js";
import "../../blocks/modules/get-up/get-up.js";
import "../../blocks/modules/catalog-filter/catalog-filter.js";
import "../../blocks/modules/catalog-page/catalog-page.js";
